### ISSUE TITLE
Build Fail on Mac OS X as at 14 August 2012

### ISSUE THREAD

**Issue by GoogleCodeExporter** [imuli/anic#11] opened 2015-06-17 12:33 UTC
```
What steps will reproduce the problem?
1. make
 

What is the expected output? What do you see instead?
compiled app for mac os x

What version of the product are you using? On what operating system?
Mountain Lion 10.8

Please provide any additional information below.
make all
anic ANI Compiler Makefile

Cleaning build output...
Building version controller...
Building lexer structure generator...
Generating lexer structures...
Compiling lexer structure object...
Building parser structure generator...
Building parser table generator...
Constructing parser table...
Generating parser structures...
Stamping version...
./bld/getChecksumProgram.sh: line 6: type: sha256sum: not found
Version stamp is 0.74.2.18062183
Building main executable...
src/types.cpp: In member function ‘TypeStatus::operator uintptr_t() const’:
src/types.cpp:1514: error: cast from ‘Type*’ to ‘unsigned int’ loses 
precision
make: *** [anic] Error 1


```

Original issue reported on code.google.com by `hjo...@qsens.net` on 14 Aug 2012 at 8:50

**Comment by imuli** [comment] 2015-06-17 13:28
Duplicate of #9.

**Closed by imuli** 2015-06-17 13:28 UTC
Labels: auto-migrated, Priority-Medium, Type-Defect
